---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: install wget , tree , git
    apt:
     name: "{{ item }}"
     state: present
    with_items:
     - git
     - wget
     - tree
     