---
- hosts: ubuntu
  become: yes
  tasks:
  - name: i want install webserver on ubuntu
    apt:
      name: apache2
      state: present
  - name: start service
    service:
      name: apache2
      state: started
  - name: i want copy files
    template:
      src: index.j2
      dest: /var/www/html/index.html