---
- hosts: all
  become: yes
  tasks:
  - name: install apache2 on ubuntu
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"
  - name: start apache2 
    service:
     name: apache2
     state: started
    when: ansible_os_family == "Debian"
  - name: install webserver httpd on amazon
    yum:
     name: httpd
     state: present
    when: ansible_os_family == "RedHat"
  - name: start httpd server
    service:
     name: httpd
     state: started
    when: ansible_os_family == "RedHat" 



